server:
  port: 9999

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservicewallet
          uri: http://localhost:8020
          predicates:
            - Path=/api/wallet/**
            - Path=/api/client/**
            - Path=/api/prospect/**
        - id: microservicenotification
          uri: http://localhost:8070
          predicates:
            - Path=/api/notification/**
            - Path=/api/venage/**
        - id: microservicetransfer
          uri: http://localhost:8090
          predicates:
            - Path=/api/transfer/**
            - Path=/api/pdftransfer/**
            - Path=/supervisors/*
        - id: microserviceuser
          uri: http://localhost:8010
          predicates:
            - Path=/api/kyc/**
            - Path=/api/siron/**


  #microserviceuser
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
